import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Typography } from "@mui/material";
import BackgroundWrapper from "@/components/BackgroundWrapper";
import Intro from "@/components/Intro";
import Wrapper from "@/components/Wrapper";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kunal Sharma - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <BackgroundWrapper>
          <Wrapper>
            <Intro />
          </Wrapper>
        </BackgroundWrapper>
      </Box>
    </>
  );
}
